# Generated by Django 4.2.3 on 2024-04-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_id", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
