# Generated by Django 4.1.13 on 2024-05-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mongo_micro_1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpendwiseBasicDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(max_length=200)),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (1, "Food"),
                            (2, "Transportation"),
                            (3, "Entertainment"),
                        ],
                        default=1,
                    ),
                ),
                ("price", models.FloatField()),
            ],
        ),
    ]
