# Generated by Django 4.1.13 on 2024-05-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mongo_micro_1", "0003_alter_spendwisebasicdetails_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spendwisebasicdetails",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
