# Generated by Django 4.1.13 on 2024-06-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_micro_1', '0004_alter_spendwisebasicdetails_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendwisebasicdetails',
            name='s_faction',
            field=models.FloatField(default=2.5),
        ),
        migrations.AlterField(
            model_name='spendwisebasicdetails',
            name='category',
            field=models.IntegerField(choices=[(1, 'Food'), (2, 'Transportation'), (3, 'Entertainment'), (4, 'Health'), (5, 'Others')], default=1),
        ),
    ]
