# Generated by Django 4.1.13 on 2024-06-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_micro_1', '0005_spendwisebasicdetails_s_faction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendwisebasicdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='spendwisebasicdetails',
            name='category',
            field=models.IntegerField(choices=[(1, 'Food'), (2, 'Apartment'), (3, 'Petrol'), (4, 'Regret'), (5, 'Luxury'), (6, 'Others'), (7, 'Investment'), (8, 'Home'), (9, 'Debt'), (10, 'Travel'), (11, 'Self Care'), (12, 'Donations')], default=1),
        ),
    ]
